let picks=JSON.parse(localStorage.getItem('picks')||'[]');
function calcAI(p){let prob=+p.prob||0,f=+p.forebet||0,t=+p.tipsters||0,s=+p.stats||0,odds=+p.odds||0;let implied=odds?100/odds:0;let value=prob-implied;let ai=Math.max(0,Math.min(100,prob*.35+f*.2+t*.15+s*.2+Math.max(-15,Math.min(20,value))*0.5+(odds>=1.7&&odds<=2.4?5:0)));return{ai,implied,value}}
function cls(n){return n>=85?'good':n>=70?'warn':'bad'}function save(){localStorage.setItem('picks',JSON.stringify(picks))}
function showTab(id,btn){document.querySelectorAll('section').forEach(s=>s.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');render()}
function addPick(){let p={id:Date.now(),date:new Date().toISOString().slice(0,10),match:match.value,sport:sport.value,league:league.value,market:market.value,prediction:prediction.value,odds:+odds.value,stake:+stake.value,prob:+prob.value,forebet:+forebet.value,tipsters:+tipsters.value,stats:+stats.value,bookmaker:bookmaker.value,notes:notes.value,result:'Pending'};picks.unshift(p);save();render();alert('Добавено')}
function settle(id,res){picks=picks.map(p=>p.id==id?{...p,result:res}:p);save();render()}function delPick(id){picks=picks.filter(p=>p.id!=id);save();render()}
function profit(p){if(p.result==='Won')return p.stake*(p.odds-1);if(p.result==='Lost')return -p.stake;return 0}
function render(){let sport=document.getElementById('fSport')?.value||'',minS=+(document.getElementById('fScore')?.value||0),minV=+(document.getElementById('fValue')?.value||-999),sort=document.getElementById('fSort')?.value||'score';let rows=picks.map(p=>({...p,...calcAI(p)})).filter(p=>(!sport||p.sport===sport)&&p.ai>=minS&&p.value>=minV);rows.sort((a,b)=>sort==='value'?b.value-a.value:sort==='odds'?b.odds-a.odds:b.ai-a.ai);pickRows.innerHTML=rows.map((p,i)=>`<tr><td>${i+1}</td><td><b>${esc(p.match)}</b><br><span class="muted">${esc(p.sport)} • ${esc(p.league)}</span></td><td>${esc(p.market)}</td><td>${esc(p.prediction)}</td><td>${p.odds.toFixed(2)}</td><td>${p.prob.toFixed(1)}%</td><td class="${p.value>=0?'good':'bad'}">${p.value.toFixed(1)}%</td><td><span class="score ${cls(p.ai)}">${p.ai.toFixed(0)}</span><div class="bar"><div style="width:${p.ai}%"></div></div></td><td><span class="pill">Forebet ${p.forebet}%</span><span class="pill">Tipsters ${p.tipsters}%</span><span class="pill">Stats ${p.stats}%</span></td><td><button class="green" onclick="settle(${p.id},'Won')">Won</button> <button class="danger" onclick="settle(${p.id},'Lost')">Lost</button></td></tr>`).join('')||'<tr><td colspan="10" class="muted">Няма селекции.</td></tr>';journalRows.innerHTML=picks.map((p,i)=>{let c=calcAI(p),pl=profit(p);return `<tr><td>${i+1}</td><td><b>${esc(p.match)}</b><br><span class="muted">${esc(p.date)} • ${esc(p.league)}</span></td><td>${esc(p.market)}<br>${esc(p.prediction)}</td><td>${(+p.odds).toFixed(2)}</td><td>${(+p.stake).toFixed(2)}€</td><td class="${cls(c.ai)}">${c.ai.toFixed(0)}</td><td>${p.result}</td><td class="${pl>=0?'good':'bad'}">${pl.toFixed(2)}€</td><td><button class="green" onclick="settle(${p.id},'Won')">Won</button> <button class="danger" onclick="settle(${p.id},'Lost')">Lost</button> <button class="secondary" onclick="settle(${p.id},'Pending')">Pending</button> <button class="danger" onclick="delPick(${p.id})">X</button></td></tr>`}).join('')||'<tr><td colspan="9" class="muted">Няма дневник.</td></tr>';let settled=picks.filter(p=>p.result!=='Pending'),won=settled.filter(p=>p.result==='Won').length,invested=settled.reduce((s,p)=>s+(+p.stake||0),0),prof=settled.reduce((s,p)=>s+profit(p),0),avgAI=picks.length?picks.reduce((s,p)=>s+calcAI(p).ai,0)/picks.length:0;sTotal.textContent=settled.length;sWon.textContent=won;sRate.textContent=settled.length?(won/settled.length*100).toFixed(2)+'%':'0%';sInvested.textContent=invested.toFixed(2)+'€';sProfit.textContent=prof.toFixed(2)+'€';sProfit.className='num '+(prof>=0?'good':'bad');sRoi.textContent=invested?(prof/invested*100).toFixed(2)+'%':'0%';sRoi.className='num '+(prof>=0?'good':'bad');sAi.textContent=avgAI.toFixed(0)}
function seedData(){picks=[{id:1,date:'2026-07-05',match:'Arsenal - Chelsea',sport:'Football',league:'Premier League',market:'Over 2.5 Goals',prediction:'Over 2.5',odds:1.88,stake:10,prob:61,forebet:58,tipsters:60,stats:64,bookmaker:'Bet365',notes:'High xG and recent overs',result:'Pending'},{id:2,date:'2026-07-05',match:'Sinner - Rune',sport:'Tennis',league:'ATP',market:'Total Games',prediction:'Over 21.5 games',odds:1.91,stake:10,prob:59,forebet:57,tipsters:55,stats:62,bookmaker:'Winbet',notes:'Serve hold rate strong',result:'Pending'}];save();render()}
async function checkHealth(){let r=await fetch('/api/health');apiOutput.textContent=JSON.stringify(await r.json(),null,2)}
async function loadFootyStats(){let r=await fetch('/api/footystats/todays-matches');apiOutput.textContent=JSON.stringify(await r.json(),null,2);document.querySelectorAll('section').forEach(s=>s.classList.add('hidden'));document.getElementById('api').classList.remove('hidden')}
function resetAll(){if(confirm('Сигурен ли си?')){picks=[];save();render()}}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}render();
